/* =========================================================
   DATA PENYEDIA LAYANAN AI (API / Aggregator / Toko Akun)
   Sumber: catatan manual, struktur ulang agar rapi.
   Tambah/edit entry di sini saja — index & detail otomatis ikut.
   ========================================================= */

const PROVIDERS = [
  {
    id: "zytroapi",
    termsUrl: "https://zytroapi.my.id/terms-of-service",
    privacyUrl: "https://zytroapi.my.id/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "ZytroAPI",
    url: "https://zytroapi.my.id/",
    pricingUrl: "https://zytroapi.my.id/#harga",
    type: "API Provider",
    tagline: "API provider dengan koleksi model SOTA & China flagship.",
    models: 38,
    modelTypes: ["SOTA", "China Flagship"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Pay as you go",
    status: "active",
    features: [
      "API provider murni (teks)",
      "38 model tersedia",
      "Fokus model SOTA & China flagship",
    ],
    notes: [
      "Daftar harga tersedia langsung di halaman utama pada bagian #harga.",
    ],
  },
  {
    id: "nanogpt",
    modelListNote: "Pengecualian: jumlahnya terlalu banyak (1000+) untuk dilist manual — hanya dicatat jumlah per kategori di atas.",
    termsUrl: "https://nano-gpt.com/legal/terms-of-service",
    privacyUrl: "https://nano-gpt.com/legal/privacy-policy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "NanoGPT",
    url: "https://nano-gpt.com",
    pricingUrl: "https://nano-gpt.com/pricing",
    type: "Aggregator",
    tagline: "Aggregator & API provider — teks, image gen, video gen, dan TTS.",
    models: 594 + 216 + 170 + 8 + 87,
    modelCounts: { Teks: 594, Gambar: 216, Video: 170, "3D": 8, "TTS / audio": 87 },
    modelTypes: ["SOTA", "Open Source", "China"],
    currency: "USD ($)",
    payment: ["Kartu", "Crypto"],
    scheme: "Pay as you go atau subscription $12/bulan",
    status: "active",
    features: [
      "Aggregator + API provider",
      "Teks, image generation, video generation, 3D, dan TTS / audio",
      "594 model teks, 216 gambar, 170 video, 8 model 3D, dan 87 TTS / audio",
    ],
    notes: [
      "Deposit hanya via kartu atau crypto dengan minimum $5.",
    ],
  },
  {
    id: "cosmoshubid",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "CosmosHub ID",
    url: "https://t.me/CosmosHubID",
    pricingUrl: null,
    type: "Telegram Shop",
    tagline: "Toko berbasis Telegram — API provider sekaligus toko akun.",
    models: 55,
    modelTypes: ["SOTA", "China"],
    currency: "IDR (Rp)",
    payment: ["QRIS", "Via Telegram"],
    scheme: "Transaksi via chat",
    status: "active",
    features: [
      "Telegram shop base",
      "API provider + toko akun (account shop)",
      "55 model: SOTA + China",
    ],
    notes: [
      "Wajib punya akun Telegram untuk bertransaksi.",
      "Semua transaksi dilakukan langsung lewat chat Telegram.",
    ],
  },
  {
    id: "pecutopus",
    termsUrl: "https://pecutopus.web.id/terms",
    privacyUrl: "https://pecutopus.web.id/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "PecutOpus",
    url: "https://pecutopus.web.id/",
    pricingUrl: "https://pecutopus.web.id/#faq",
    type: "API Provider",
    tagline: "API provider dengan sistem paket harian sampai bulanan.",
    models: 30,
    modelTypes: ["SOTA", "China", "Jailbreak"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Paket harian – bulanan",
    status: "active",
    features: [
      "30 model tersedia",
      "Sistem paket harian sampai bulanan",
      "Support via Telegram",
      "Punya set model khusus yang sudah di-jailbreak",
    ],
    notes: [
      "Skema harga lengkap bisa dilihat di bagian #faq situsnya.",
    ],
  },
  {
    id: "rentalmail",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "RentalMail",
    url: "https://www.rentalmail.my.id/",
    pricingUrl: null,
    type: "Layanan Lain",
    tagline: "Layanan temp mail premium — basis sewa (rent).",
    models: 0,
    modelTypes: [],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Sewa (rent)",
    status: "active",
    features: [
      "Semacam layanan temporary mail premium",
      "Basis sewa, bukan sekali beli",
    ],
    notes: [
      "Bukan penyedia model AI — layanan pendukung (email temporer sewa).",
    ],
  },
  {
    id: "ruvicode",
    termsUrl: "https://ruvicode.com/legal/terms",
    privacyUrl: "https://ruvicode.com/legal/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: true,
    name: "RuviCode",
    url: "https://ruvicode.com/",
    pricingUrl: "https://ruvicode.com/",
    type: "API Provider",
    tagline: "API provider SOTA & China — harga di bawah official.",
    models: 30,
    modelTypes: ["SOTA", "China"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Pay as you go",
    status: "active",
    features: [
      "30+ model tersedia",
      "Model SOTA dan China",
      "Harga lebih murah dibanding harga official",
    ],
    notes: [
      "Meski di bawah harga official, harga masih terbilang lumayan mahal.",
    ],
  },
  {
    id: "digicodestore",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "DigiCode Store",
    url: "https://digicodestore.my.id",
    pricingUrl: "https://digicodestore.my.id/katalog.php",
    type: "Account Store",
    tagline: "Toko akun — AI, streaming, VPN, dan barang misc.",
    models: 0,
    modelTypes: [],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Beli akun",
    status: "active",
    features: [
      "Account store (toko akun)",
      "Kategori: AI, streaming, VPN, dan misc",
    ],
    notes: [
      "Katalog lengkap tersedia di halaman katalog.php.",
    ],
  },
  {
    id: "modelrouter",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: true,
    name: "ModelRouter",
    url: "https://modelrouter.id/models",
    pricingUrl: "https://modelrouter.id/models",
    type: "Aggregator",
    tagline: "Semacam OpenRouter versi Indonesia.",
    models: 40,
    modelTypes: ["SOTA", "China"],
    currency: "USD ($)",
    payment: ["QRIS"],
    scheme: "Pay as you go (kredit pemakaian USD)",
    status: "active",
    features: [
      "Konsep mirip OpenRouter tapi lokal (Indonesia)",
      "40+ model SOTA dan China",
    ],
    notes: [
      "Harga relatif sama dengan API official (tidak jauh beda).",
      "Kredit pemakaian dalam USD; deposit via QRIS dibayar dalam Rupiah.",
    ],
  },
  {
    id: "kiosapi",
    termsUrl: "https://kiosapi.com/user-agreement",
    privacyUrl: "https://kiosapi.com/privacy-policy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: true,
    name: "KiosAPI",
    url: "https://kiosapi.com/",
    pricingUrl: "https://kiosapi.com/",
    type: "API Provider",
    tagline: "API provider multibahasa — teks & gambar dengan pilihan mata uang USD / IDR.",
    models: 70,
    modelTypes: [],
    currency: "USD ($) / IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Harga USD / IDR sesuai pengaturan",
    status: "active",
    features: [
      "70+ model tersedia",
      "Pilihan mata uang USD / IDR di pengaturan",
      "Antarmuka multibahasa",
      "API tersedia untuk teks dan gambar",
    ],
    notes: [
      "Penting: cek dulu ketersediaan model di API sebelum memutuskan memakai layanan ini.",
    ],
  },
  {
    id: "unorouter",
    termsUrl: "https://unorouter.com/id/ketentuan",
    privacyUrl: "https://unorouter.com/id/privasi",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    statusCheck: "skip",   // situs menolak request otomatis (bot-block) — dicek manual saja
    modelsApprox: false,
    name: "UnoRouter",
    url: "https://unorouter.com/id",
    pricingUrl: "https://unorouter.com/id",
    type: "Aggregator",
    tagline: "Router model lengkap — 239 model, T2I sampai embedding.",
    models: 239,
    modelTypes: ["SOTA", "China", "Open Source"],
    currency: "USD ($)",
    payment: ["Kartu", "Crypto", "PayPal"],
    scheme: "Pay as you go",
    status: "active",
    features: [
      "239 model tersedia",
      "Antarmuka multibahasa",
      "Text-to-image dan embedding",
      "Model SOTA, China, dan open source",
    ],
    notes: [
      "Hanya USD; deposit minimum $1 via kartu, crypto, atau PayPal. Tidak mendukung QRIS.",
    ],
  },
  {
    id: "tokenkoding",
    termsUrl: "https://tokenkoding.id/syarat",
    privacyUrl: "https://tokenkoding.id/privasi",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "TokenKoding",
    url: "https://tokenkoding.id",
    pricingUrl: "https://tokenkoding.id/harga",
    type: "API Provider",
    tagline: "API provider pay as you go dengan 47 model, hosting, dan WhatsApp API.",
    models: 47,
    modelTypes: ["SOTA", "Eropa", "China", "Open Source"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Pay as you go",
    status: "active",
    features: [
      "API provider dengan 47 model dan skema pay as you go",
      "Hosting dengan paket Small, Hobby, dan Scale",
      "WhatsApp API",
      "Model SOTA, Eropa, China, dan open source",
    ],
    notes: [
      "Harga Claude hampir sama — bahkan bisa lebih murah — dibanding API official.",
    ],
  },
  {
    id: "kelontongai",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "KelontongAI",
    url: "https://kelontongai.id/",
    pricingUrl: "https://kelontongai.id/",
    type: "API Provider",
    tagline: "API provider murah — paket 7 sampai 60 hari.",
    models: 0,
    modelTypes: [],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Paket 7 – 60 hari",
    status: "active",
    features: [
      "Harga tergolong murah",
      "Sistem paket dengan durasi 7 hari sampai 60 hari",
    ],
    notes: [
      "Bukan pay as you go — harus beli paket berdurasi.",
    ],
  },
  {
    id: "oaoclipora",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "OAO Clipora",
    url: "https://oao.clipora.buzz/",
    pricingUrl: "https://oao.clipora.buzz/",
    type: "API Provider",
    tagline: "Sistem paket VIP & unlimited berbasis waktu.",
    models: 0,
    modelTypes: [],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Paket VIP / unlimited / waktu",
    status: "active",
    features: [
      "Sistem paket berbasis waktu",
      "Ada tier VIP dan unlimited",
    ],
    notes: [],
  },
  {
    id: "ninerouter",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "9Router",
    url: "https://9router.com/",
    pricingUrl: "https://9router.com/",
    type: "Local Gateway",
    tagline: "Gateway lokal open-source untuk Cursor, Claude Code, dan Cline.",
    models: 0,
    modelTypes: [],
    currency: "Tidak berlaku (software lokal)",
    payment: [],
    scheme: "Software lokal open-source; biaya mengikuti provider yang dihubungkan",
    status: "active",
    features: [
      "Gateway lokal open-source untuk Cursor, Claude Code, dan Cline",
      "Fallback otomatis ke model gratis atau lebih murah saat kuota habis",
      "Mendukung 60+ provider dan ratusan model",
      "Translasi format API OpenAI / Claude",
      "RTK diklaim dapat mengompresi hingga 40% menurut catatan manual; bukan jaminan",
    ],
    notes: [
      "Software gateway lokal, bukan toko kredit API; pembayaran dan biaya bergantung pada provider yang dihubungkan.",
      "Dukungan provider/model dan klaim kompresi RTK berasal dari catatan manual, belum diverifikasi langsung.",
    ],
  },
  {
    id: "dahono",
    termsUrl: "https://router.dahono.com/terms",
    privacyUrl: "https://router.dahono.com/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: true,
    name: "Dahono Router",
    url: "https://router.dahono.com/",
    pricingUrl: "https://router.dahono.com/",
    type: "Infrastruktur",
    tagline: "Ekosistem infrastruktur AI & cloud — API gateway, agen otonom, VPS, dan S3 storage.",
    models: 46,
    modelTypes: ["SOTA", "China"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Pay as you go (Dahono Credit)",
    status: "active",
    features: [
      "AI Gateway API: 46+ model SOTA & China via satu endpoint",
      "Hermes Agent: VM pribadi dengan agen AI 24/7, integrasi Telegram",
      "Managed LTM MCP: long-term memory hybrid knowledge graph (Claude Desktop, Cursor, Windsurf)",
      "NAT VPS Cloud: server Linux root penuh, 100 port forwarded, 1 Gbps",
      "AI Architect: canvas visual node-based untuk rancang & deploy agent",
      "S3 Object Storage untuk dataset, backup, dan aset aplikasi",
      "5+ layanan cloud lainnya",
      "Jaminan privasi Zero Data Retention",
      "Tier otomatis (Free/Starter/Pro/Dedicated) berdasarkan saldo",
    ],
    notes: [
      "Tier Free memberi bonus saldo awal 100 credit, cocok untuk coba-coba.",
      "Semua layanan dibayar pakai Dahono Credit, pay as you go.",
    ],
  },
  {
    id: "sumopod",
    termsUrl: "https://sumopod.com/terms",
    privacyUrl: "https://sumopod.com/privacy-policy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "SumoPod",
    url: "https://sumopod.com/",
    pricingUrl: "https://sumopod.com/",
    type: "Infrastruktur",
    tagline: "RunPod versi lokal — sewa GPU cloud + API, pembayaran Rupiah.",
    models: 0,
    modelTypes: [],
    currency: "IDR (Rp)",
    payment: ["QRIS", "Transfer bank", "Kartu"],
    scheme: "Deposit mulai Rp50.000",
    status: "active",
    features: [
      "Sewa GPU cloud ala RunPod, versi lokal Indonesia",
      "Menyediakan API juga",
      "Pembayaran: QRIS, transfer bank, dan kartu",
      "Deposit mulai dari 50 ribu Rupiah",
    ],
    notes: [
      "Fokus utama infrastruktur GPU; juga menyediakan akses API.",
    ],
  },
];

// Ekspor untuk Node (dipakai scripts/check-status.js di GitHub Actions); di browser baris ini tidak berpengaruh.
if (typeof module !== "undefined" && module.exports) module.exports = PROVIDERS;
