/* =========================================================
   DATA PENYEDIA LAYANAN AI (API / Aggregator / Toko Akun)
   Sumber: catatan manual, struktur ulang agar rapi.
   Tambah/edit entry di sini saja — index & detail otomatis ikut.
   ========================================================= */

const PROVIDERS = [
  {
    id: "zytroapi",
    termsUrl: "https://zytroapi.my.id/terms-of-service",
    privacyUrl: "https://zytroapi.my.id/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "ZytroAPI",
    url: "https://zytroapi.my.id/",
    pricingUrl: "https://zytroapi.my.id/#harga",
    type: "API Provider",
    tagline: "API provider dengan koleksi model SOTA & China flagship.",
    models: 71,
    modelTypes: ["SOTA", "China Flagship"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Pay as you go",
    status: "active",
    features: [
      "API provider murni (teks)",
      "64 model terdata dari unggahan crawl 25 Sep 2026",
      "Fokus model SOTA & China flagship",
    ],
    notes: [
      "Daftar harga tersedia langsung di halaman utama pada bagian #harga.",
    ],
  },
  {
    id: "nanogpt",
    modelListNote: "Pengecualian: jumlahnya terlalu banyak (1000+) untuk dilist manual — hanya dicatat jumlah per kategori di atas.",
    termsUrl: "https://nano-gpt.com/legal/terms-of-service",
    privacyUrl: "https://nano-gpt.com/legal/privacy-policy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "NanoGPT",
    url: "https://nano-gpt.com",
    pricingUrl: "https://nano-gpt.com/pricing",
    type: "Aggregator",
    tagline: "Aggregator & API provider — teks, image gen, video gen, dan TTS.",
    models: 594 + 216 + 170 + 8 + 87,
    modelCounts: { Teks: 594, Gambar: 216, Video: 170, "3D": 8, "TTS / audio": 87 },
    modelTypes: ["SOTA", "Open Source", "China"],
    currency: "USD ($)",
    payment: ["Kartu", "Crypto"],
    scheme: "Pay as you go atau subscription $12/bulan",
    status: "active",
    features: [
      "Aggregator + API provider",
      "Teks, image generation, video generation, 3D, dan TTS / audio",
      "594 model teks, 216 gambar, 170 video, 8 model 3D, dan 87 TTS / audio",
    ],
    notes: [
      "Deposit hanya via kartu atau crypto dengan minimum $5.",
    ],
  },
  {
    id: "cosmoshubid",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "CosmosHub ID",
    url: "https://t.me/CosmosHubID",
    pricingUrl: null,
    type: "Telegram Shop",
    tagline: "Toko berbasis Telegram — API provider sekaligus toko akun.",
    models: 56,
    modelTypes: ["SOTA", "China"],
    currency: "IDR (Rp)",
    payment: ["QRIS", "Via Telegram"],
    scheme: "Transaksi via chat",
    status: "active",
    features: [
      "Telegram shop base",
      "API provider + toko akun (account shop)",
      "55 model: SOTA + China",
    ],
    notes: [
      "Wajib punya akun Telegram untuk bertransaksi.",
      "Semua transaksi dilakukan langsung lewat chat Telegram.",
    ],
  },
  {
    id: "pecutopus",
    termsUrl: "https://pecutopus.web.id/terms",
    privacyUrl: "https://pecutopus.web.id/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "loaded",
    modelsApprox: false,
    name: "PecutOpus",
    url: "https://pecutopus.web.id/",
    pricingUrl: "https://pecutopus.web.id/#faq",
    type: "API Provider",
    tagline: "API provider dengan sistem paket harian sampai bulanan.",
    models: 31,
    modelTypes: ["SOTA", "China", "Jailbreak"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Paket harian – bulanan",
    status: "active",
    features: [
      "30 model tersedia",
      "Sistem paket harian sampai bulanan",
      "Support via Telegram",
      "Punya set model khusus yang sudah di-jailbreak",
    ],
    notes: [
      "Skema harga lengkap bisa dilihat di bagian #faq situsnya.",
    ],
  },
  {
    id: "rentalmail",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "RentalMail",
    url: "https://www.rentalmail.my.id/",
    pricingUrl: null,
    type: "Layanan Lain",
    tagline: "Layanan temp mail premium — basis sewa (rent).",
    models: 0,
    modelTypes: [],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Sewa (rent)",
    status: "active",
    features: [
      "Semacam layanan temporary mail premium",
      "Basis sewa, bukan sekali beli",
    ],
    notes: [
      "Bukan penyedia model AI — layanan pendukung (email temporer sewa).",
    ],
  },
  {
    id: "ruvicode",
    termsUrl: "https://ruvicode.com/legal/terms",
    privacyUrl: "https://ruvicode.com/legal/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "RuviCode",
    url: "https://ruvicode.com/",
    pricingUrl: "https://ruvicode.com/",
    type: "API Provider",
    tagline: "API provider SOTA & China — harga di bawah official.",
    models: 42,
    modelTypes: ["SOTA", "China"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Pay as you go",
    status: "active",
    features: [
      "42 model terverifikasi dari katalog live 24 Sep 2026",
      "Model SOTA dan China",
      "Harga lebih murah dibanding harga official",
    ],
    notes: [
      "Meski di bawah harga official, harga masih terbilang lumayan mahal.",
    ],
  },
  {
    id: "modelrouter",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "ModelRouter",
    url: "https://modelrouter.id/models",
    pricingUrl: "https://modelrouter.id/models",
    type: "Aggregator",
    tagline: "Semacam OpenRouter versi Indonesia.",
    models: 55,
    modelTypes: ["SOTA", "China"],
    currency: "USD ($)",
    payment: ["QRIS"],
    scheme: "Pay as you go (kredit pemakaian USD)",
    status: "active",
    features: [
      "Konsep mirip OpenRouter tapi lokal (Indonesia)",
      "55 model terdata dari unggahan crawl 25 Sep 2026",
    ],
    notes: [
      "Harga relatif sama dengan API official (tidak jauh beda).",
      "Kredit pemakaian dalam USD; deposit via QRIS dibayar dalam Rupiah.",
    ],
  },
  {
    id: "kiosapi",
    termsUrl: "https://kiosapi.com/user-agreement",
    privacyUrl: "https://kiosapi.com/privacy-policy",
    legalNote: null,
    modelList: [],
    modelListStatus: "loaded",
    modelsApprox: false,
    name: "KiosAPI",
    url: "https://kiosapi.com/",
    pricingUrl: "https://kiosapi.com/",
    type: "API Provider",
    tagline: "API provider multibahasa — teks & gambar dengan pilihan mata uang USD / IDR.",
    models: 62,
    modelTypes: [],
    currency: "USD ($) / IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Harga USD / IDR sesuai pengaturan",
    status: "active",
    features: [
      "70+ model tersedia",
      "Pilihan mata uang USD / IDR di pengaturan",
      "Antarmuka multibahasa",
      "API tersedia untuk teks dan gambar",
    ],
    notes: [
      "Penting: cek dulu ketersediaan model di API sebelum memutuskan memakai layanan ini.",
    ],
  },
  {
    id: "unorouter",
    termsUrl: "https://unorouter.com/id/ketentuan",
    privacyUrl: "https://unorouter.com/id/privasi",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    statusCheck: "skip",   // situs menolak request otomatis (bot-block) — dicek manual saja
    modelsApprox: false,
    name: "UnoRouter",
    url: "https://unorouter.com/id",
    pricingUrl: "https://unorouter.com/id",
    type: "Aggregator",
    tagline: "Router model lengkap — 239 model, T2I sampai embedding.",
    models: 239,
    modelTypes: ["SOTA", "China", "Open Source"],
    currency: "USD ($)",
    payment: ["Kartu", "Crypto", "PayPal"],
    scheme: "Pay as you go",
    status: "active",
    features: [
      "239 model tersedia",
      "Antarmuka multibahasa",
      "Text-to-image dan embedding",
      "Model SOTA, China, dan open source",
    ],
    notes: [
      "Hanya USD; deposit minimum $1 via kartu, crypto, atau PayPal. Tidak mendukung QRIS.",
    ],
  },
  {
    id: "tokenkoding",
    termsUrl: "https://tokenkoding.id/syarat",
    privacyUrl: "https://tokenkoding.id/privasi",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "TokenKoding",
    url: "https://tokenkoding.id",
    pricingUrl: "https://tokenkoding.id/harga",
    type: "API Provider",
    tagline: "API provider pay as you go dengan 46 model, hosting, dan WhatsApp API.",
    models: 46,
    modelTypes: ["SOTA", "Eropa", "China", "Open Source"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Pay as you go",
    status: "active",
    features: [
      "API provider dengan 46 model terverifikasi dari endpoint pricing publik",
      "Hosting dengan paket Small, Hobby, dan Scale",
      "WhatsApp API",
      "Model SOTA, Eropa, China, dan open source",
    ],
    notes: [
      "Harga Claude hampir sama — bahkan bisa lebih murah — dibanding API official.",
    ],
  },
  {
    id: "kelontongai",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "KelontongAI",
    url: "https://kelontongai.id/",
    pricingUrl: "https://kelontongai.id/",
    type: "API Provider",
    tagline: "API provider murah — paket 7 sampai 60 hari.",
    models: 36,
    modelTypes: [],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Paket 7 – 60 hari",
    status: "active",
    features: [
      "Harga tergolong murah",
      "Sistem paket dengan durasi 7 hari sampai 60 hari",
    ],
    notes: [
      "Bukan pay as you go — harus beli paket berdurasi.",
    ],
  },
  {
    id: "oaoclipora",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "OAO Clipora",
    url: "https://oao.clipora.buzz/",
    pricingUrl: "https://oao.clipora.buzz/",
    type: "API Provider",
    tagline: "Sistem paket VIP & unlimited berbasis waktu.",
    models: 21,
    modelTypes: [],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Paket VIP / unlimited / waktu",
    status: "active",
    features: [
      "Sistem paket berbasis waktu",
      "Ada tier VIP dan unlimited",
    ],
    notes: [],
  },
  {
    id: "ninerouter",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "9Router",
    url: "https://9router.com/",
    pricingUrl: "https://9router.com/",
    type: "Local Gateway",
    tagline: "Gateway lokal open-source untuk Cursor, Claude Code, dan Cline.",
    models: 60,
    modelListNote: "Angka 60 = jumlah API provider yang didukung (bukan jumlah model) — 9Router gateway, bukan penyedia model.",
    modelTypes: [],
    currency: "$ (hanya display estimasi — 9Router sendiri tidak pernah menagih)",
    payment: [],
    scheme: "9Router = FREE forever (open source, tidak pernah menagih). Kamu bayar langsung ke provider yang dipakai (subscripsi atau fee API); provider gratis tetap gratis.",
    status: "active",
    features: [
      "Gateway lokal open-source untuk Cursor, Claude Code, dan Cline",
      "Mendukung 60 API provider (ratusan model via provider-provider tersebut)",
      "Fallback otomatis ke model gratis atau lebih murah saat kuota habis",
      "Translasi format API OpenAI / Claude",
      "RTK diklaim dapat mengompresi hingga 40% menurut catatan manual; bukan jaminan",
    ],
    notes: [
      "Software 9Router gratis selamanya — open source, tidak pernah mengirim invoice atau mencharge kartu.",
      "\"Biaya\" di dashboard hanyalah display estimasi biaya API berbayar (alat perbandingan penghematan), BUKAN tagihan. Contoh: display $290 di provider free-tier = itu nominal yang kamu hemat, bukan yang kamu bayar.",
      "Provider gratis tetap gratis (mis. Kiro ~50 kredit/bln, OpenCode Free, Vertex $300 kredit = $0 dalam batas free tier). Catatan: free tier iFlow/Qwen/Gemini CLI sudah dihentikan sejak 2026.",
      "Aturan bayar: provider subscripsi (Claude Code, Codex) dibayar langsung di situsnya; provider murah (GLM, MiniMax) dibayar langsung ke provider — 9Router hanya merutekan.",
    ],
  },
  {
    id: "dahono",
    termsUrl: "https://router.dahono.com/terms",
    privacyUrl: "https://router.dahono.com/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "Dahono Router",
    url: "https://router.dahono.com/",
    pricingUrl: "https://router.dahono.com/",
    type: "Infrastruktur",
    tagline: "Ekosistem infrastruktur AI & cloud — API gateway, agen otonom, VPS, dan S3 storage.",
    models: 35,
    modelTypes: ["SOTA", "China"],
    currency: "IDR (Rp)",
    payment: ["QRIS"],
    scheme: "Pay as you go (Dahono Credit)",
    status: "active",
    features: [
      "AI Gateway API: 46+ model SOTA & China via satu endpoint",
      "Hermes Agent: VM pribadi dengan agen AI 24/7, integrasi Telegram",
      "Managed LTM MCP: long-term memory hybrid knowledge graph (Claude Desktop, Cursor, Windsurf)",
      "NAT VPS Cloud: server Linux root penuh, 100 port forwarded, 1 Gbps",
      "AI Architect: canvas visual node-based untuk rancang & deploy agent",
      "S3 Object Storage untuk dataset, backup, dan aset aplikasi",
      "5+ layanan cloud lainnya",
      "Jaminan privasi Zero Data Retention",
      "Tier otomatis (Free/Starter/Pro/Dedicated) berdasarkan saldo",
    ],
    notes: [
      "Tier Free memberi bonus saldo awal 100 credit, cocok untuk coba-coba.",
      "Semua layanan dibayar pakai Dahono Credit, pay as you go.",
    ],
  },
  {
    id: "aihorde",
    termsUrl: "https://aihorde.net/terms",
    privacyUrl: "https://aihorde.net/register",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "AI Horde",
    url: "https://aihorde.net/",
    pricingUrl: "https://aihorde.net/faq",
    type: "Distributed Computing",
    tagline: "Crowdsourced cluster gratis untuk generate teks, gambar, dan video.",
    models: 50,
    modelsApprox: true,
    modelTypes: [],
    currency: "Gratis (Kudos, bukan uang)",
    payment: [],
    scheme: "Gratis — 100% volunteer-run, didukung GPU yang dibagikan komunitas",
    status: "active",
    features: [
      "Generate teks, gambar, dan video gratis",
      "50+ model beragam — daftar modelnya dinamis/random, mengikuti demand dan worker yang aktif di horde",
      "Semua orang bisa membagikan GPU/PC mereka sebagai worker",
      "Sistem Kudos: prioritas antrean naik jika berkontribusi",
      "Bisa dipakai anonim (API key 0000000000) dengan prioritas terendah",
      "API terbuka dan lengkap dengan dokumentasi Swagger",
    ],
    notes: [
      "Pionir era awal AI generatif — asal-usul dari Stable Horde.",
      "Open source, dikelola Haidra Org di GitHub.",
      "Bukan blockchain/crypto walau ada sistem Kudos, dan bukan startup yang akan mati kehabisan dana — sepenuhnya volunteer.",
      "Kredensial: cukup ID akun provider, tidak ada data lain yang disimpan.",
      "Info lebih lanjut: komunitas Discord resmi.",
    ],
  },
  {
    id: "dezgo",
    termsUrl: "https://dezgo.com/terms",
    privacyUrl: "https://dezgo.com/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "Dezgo",
    url: "https://dezgo.com/",
    pricingUrl: "https://dev.dezgo.com/",
    type: "API Provider",
    tagline: "Spesialis image generation: SD, SDXL, Flux, model anime dan SOTA.",
    models: 114,
    modelsApprox: false,
    modelTypes: ["SOTA", "China", "Open Source"],
    currency: "$",
    payment: [],
    scheme: "Pay as you go, deposit credit",
    status: "active",
    features: [
      "Spesialis image gen — awalnya fokus anime & Stable Diffusion, lalu berkembang",
      "Text-to-image, image-to-image, inpainting, controlnet, upscaling, remove-background",
      "100+ model siap pakai (Flux, SDXL Lightning, Dreamshaper, Pony Diffusion, dll)",
      "Support import LoRA untuk karakter/style custom",
      "API dengan endpoint text moderation murah",
    ],
    notes: [
      "Deposit minimum $10; kredit kedaluwarsa dalam 1 tahun.",
      "Ada model gratis via web UI tapi dengan iklan dan generasi lambat.",
      "Contoh harga: 512x512 sekitar $0.0019, 1024x1024 Flux sekitar $0.0029.",
      "Dokumentasi API di dev.dezgo.com.",
    ],
  },
  {
    id: "falai",
    termsUrl: "https://fal.ai/legal/terms-of-service",
    privacyUrl: "https://fal.ai/legal/privacy-policy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    models: 1000,
    modelsApprox: true,
    name: "fal.ai",
    url: "https://fal.ai/",
    pricingUrl: "https://fal.ai/pricing",
    type: "Aggregator",
    tagline: "Perusahaan frontier awal di bisnis infrastruktur & serverless AI gen.",
    modelTypes: ["SOTA", "China", "Open Source"],
    currency: "$",
    payment: [],
    scheme: "Pay as you go, deposit credit",
    status: "active",
    features: [
      "1000+ model image, video, audio, dan 3D production-ready",
      "Serverless GPU + on-demand clusters (H100, H200, B200)",
      "Unified API dan SDK untuk ratusan model open + LoRA sendiri",
      "SOC 2 compliant, SSO, private endpoints untuk enterprise",
    ],
    notes: [
      "Deposit minimum $10; kredit kedaluwarsa dalam 1 tahun.",
      "Guardrail berat dan kebijakan ketat untuk kebanyakan model — konsekuensinya stabilitas dan kekuatan yang reliable dan terjamin.",
      "Kompetitor utama WaveSpeed.",
      "Harga GPU serverless mulai $1.89/jam (H100).",
    ],
  },
  {
    id: "marketku",
    termsUrl: "https://marketku.id/terms",
    privacyUrl: "https://marketku.id/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "Marketku",
    url: "https://marketku.id/",
    pricingUrl: "",
    type: "Toko Akun",
    tagline: "Marketplace produk digital Indonesia — termasuk produk & layanan AI.",
    models: 0,
    modelTypes: [],
    currency: "Rp",
    payment: ["QRIS", "Kartu", "Transfer bank"],
    scheme: "Marketplace (transaksi per produk)",
    status: "active",
    features: [
      "Marketplace untuk beli produk digital, termasuk produk dan layanan AI",
      "Pembayaran QRIS, kartu, dan transfer bank",
      "Siapa pun bisa jadi seller",
      "Support multi bahasa",
    ],
    notes: [
      "Ada opsi escrow/verifikasi tambahan untuk transaksi tertentu.",
      "Harga, stok, dan opsi produk bisa berubah sewaktu-waktu mengikuti update seller.",
    ],
  },
  {
    id: "runpod",
    termsUrl: "https://www.runpod.io/legal/terms-of-service",
    privacyUrl: "https://www.runpod.io/legal/privacy-policy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "RunPod",
    url: "https://www.runpod.io/",
    pricingUrl: "https://www.runpod.io/pricing",
    type: "Infrastruktur",
    tagline: "OG AI infra provider — sewa GPU/server CPU, jalankan model sendiri.",
    models: 0,
    modelTypes: [],
    currency: "$",
    payment: ["Kartu", "Crypto"],
    scheme: "Pay as you go — per jam/hari/bulan/tahun",
    status: "active",
    features: [
      "Sewa GPU: Pods (dedicated), Serverless (API inference), Clusters (multi-node hingga 64 GPU)",
      "Reserved Clusters untuk enterprise (SLA, 10.000+ GPU)",
      "Public Endpoints: model pre-deployed via API tanpa setup infra",
      "Storage mulai $0.05/GB/bulan",
      "Ribuan GPU di 30+ region",
    ],
    notes: [
      "Pembayaran via Stripe (kartu) dan Crypto.com.",
      "PERINGATAN: bisa overwhelming dan 'menjebak' jika belum paham skema harga dan mekanisme sewa pod — baca dulu mekanisme harga sebelum pakai.",
    ],
  },
  {
    id: "sumopod",
    termsUrl: "https://sumopod.com/terms",
    privacyUrl: "https://sumopod.com/privacy-policy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "SumoPod",
    url: "https://sumopod.com/",
    pricingUrl: "https://sumopod.com/",
    type: "Infrastruktur",
    tagline: "RunPod versi lokal — sewa GPU cloud + API, pembayaran Rupiah.",
    models: 0,
    modelTypes: [],
    currency: "IDR (Rp)",
    payment: ["QRIS", "Transfer bank", "Kartu"],
    scheme: "Deposit mulai Rp50.000",
    status: "active",
    features: [
      "Sewa GPU cloud ala RunPod, versi lokal Indonesia",
      "Menyediakan API juga",
      "Pembayaran: QRIS, transfer bank, dan kartu",
      "Deposit mulai dari 50 ribu Rupiah",
    ],
    notes: [
      "Fokus utama infrastruktur GPU; juga menyediakan akses API.",
    ],
  },
  {
    id: "pecutaan",
    termsUrl: null,
    privacyUrl: null,
    legalNote: "TIDAK ADA TOS dan Privacy Policy",
    modelList: [
      "auto (router otomatis, 1x)",
      "deepseek-v4-flash (2x)",
      "deepseek-v4-flash-0731 (2x)",
      "deepseek-v4-flash-vision-exp (vision, 2.5x)",
      "deepseek-v4-mod (3x)",
      "deepseek-v4-pro (1.15x)",
      "deepseek-v4-pro-0813 (1.8x)",
      "deepseek-v4.1-flash (vision, 2.56x)",
      "deepseek-v4.1-mod (vision, 3.2x)",
      "glm-5.1 (1x)",
      "glm-5.2 (1.25x)",
      "glm-5.2-mod (3x)",
      "glm-5.3 (2x)",
      "glm-5.3-flash (vision, 2x)",
      "glm-5.3-flash-mod (vision, 3.5x)",
      "glm-5.3-flashx (vision, 2.5x)",
      "glm-5.3-flashx-mod (vision, 4x)",
      "glm-5.3-mod (3.2x)",
      "gpt-5.6 (vision, 5x)",
      "gpt-5.6-luna (vision, 5x)",
      "gpt-5.6-luna-b (vision, 5x)",
      "gpt-5.6-terra (vision, 10x)",
      "gpt-5.6-terra-b (vision, 10x)",
      "hy3 (1x)",
      "hy4 (1.4x)",
      "kimi-k2.7-code (1x)",
      "kimi-k2.7-code-highspeed (1.5x)",
      "kimi-k3 (vision, 2x)",
      "kimi-k3-mod (vision, 3.5x)",
      "mimo-v2.5-pro (1.4x)",
      "minimax-m3 (1.4x)",
    ],
    modelListStatus: "loaded",
    modelListNote: "31 model per 24 Sep 2026. Angka dalam kurung = multiplier kuota (model premium memakan kuota lebih cepat). Daftar model dan status suksesnya dinamis — cek situs untuk live.",
    modelsApprox: false,
    name: "Pecut Aan",
    url: "https://pecut.aanserver.web.id/",
    pricingUrl: "https://pecut.aanserver.web.id/",
    type: "API Provider",
    tagline: "Marketplace token AI — satu kuota untuk semua model, QRIS Midtrans + crypto.",
    models: 31,
    modelTypes: ["SOTA", "China"],
    currency: "IDR (Rp)",
    payment: ["QRIS (Midtrans)", "Crypto"],
    scheme: "Paket token (10M-2B), kuota dihitung dari total pemakaian bukan per model",
    status: "active",
    features: [
      "Marketplace token AI — satu kuota token untuk semua model populer",
      "QRIS Midtrans (verifikasi otomatis) atau crypto (diperiksa admin, cocokkan TXID)",
      "8 paket: 10M Rp4.400 s.d. 2B Rp300.000 (promo aktif hampir semua paket)",
      "Sistem multiplier: model premium (GPT-5.6 Terra 10x) memakan kuota lebih cepat",
      "API key + base URL otomatis muncul di halaman order setelah bayar terverifikasi",
      "Kompatibel dengan 9router, opencode, hermes, openclaw, dan vscode",
      "Multi-bahasa (ID/EN/VI/ZH), checkout tamu tanpa akun",
      "Lacak order via ID order tanpa login",
    ],
    notes: [
      "Kelanjutan/ekosistem PecutOpus (pecut.web.id) — konsep token secepat pecut yang sama.",
      "Skema per 10M token: Rp 4.400 (paket 10M) turun ke Rp 1.500 (paket 2B) — makin besar makin murah.",
      "Paket 500M ke atas dapat prioritas verifikasi pembayaran.",
      "Varian -mod tersedia (tradisi model jailbreak ala PecutOpus).",
      "Statistik live tingkat keberhasilan per model tersedia di situs; beberapa model bisa 0% saat sedang tumbang.",
      "NMID QRIS terdaftar: ID2026PCT0091823. Kontak admin: WA 085398911943.",
      "Kredensial API tersembunyi bawaan, ditampilkan hanya saat tombol ditekan di halaman order.",
    ],
  },
  {
    id: "vastai",
    termsUrl: "https://vast.ai/terms",
    privacyUrl: "https://vast.ai/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    modelsApprox: false,
    name: "Vast.ai",
    url: "https://vast.ai/",
    pricingUrl: "https://vast.ai/pricing",
    type: "Infrastruktur",
    tagline: "Rival utama RunPod — marketplace GPU cloud dengan akses mudah.",
    models: 0,
    modelTypes: [],
    currency: "$",
    payment: [],
    scheme: "Pay as you go — sewa per jam",
    status: "active",
    features: [
      "Marketplace GPU cloud: sewa/hosting compute",
      "Serverless ready-to-deploy",
      "CLI, Python SDK, dan API lengkap (OpenAPI spec)",
      "Harga GPU live di halaman pricing",
    ],
    notes: [
      "Deposit minimum cuma $5 untuk mulai sewa (belum termasuk biaya storage).",
      "Baca TOS, terms, dan mekanisme harga dulu sebelum pakai.",
    ],
  },
  {
    id: "wavespeed",
    termsUrl: "https://wavespeed.ai/static/terms",
    privacyUrl: "https://wavespeed.ai/static/privacy",
    legalNote: null,
    modelList: [],
    modelListStatus: "awaiting-source",
    models: 1000,
    modelsApprox: true,
    name: "WaveSpeed",
    url: "https://wavespeed.ai/",
    pricingUrl: "https://wavespeed.ai/pricing",
    type: "Aggregator",
    tagline: "Web & API provider terbesar — kompetitor fal.ai.",
    modelTypes: ["SOTA", "China", "Open Source", "Eropa"],
    currency: "$",
    payment: ["Kartu", "Crypto"],
    scheme: "Pay as you go, deposit credit",
    status: "active",
    features: [
      "1000+ model multi-modal: image, video, 3D, audio, dan banyak lagi",
      "Model dari ByteDance, Google, Alibaba, OpenAI, Kuaishou, ElevenLabs, dll — satu REST API dan satu billing",
      "Image gen/edit, video gen/edit/extend, motion control + digital human, 3D asset, TTS, upscaler, watermark removal, 1000+ varian LoRA",
      "Playground interaktif per model + contoh Python/JS/cURL",
    ],
    notes: [
      "Deposit minimum $5 — kartu atau crypto.",
      "Kredit kedaluwarsa dalam 1 tahun.",
      "Hanya $ (USD).",
      "Aggregator model SOTA, China, open source, dan Eropa.",
      "Katalog model: wavespeed.ai/models.",
    ],
  },
];

/* ===== Scam List =====
 * Daftar layanan yang dilaporkan scam oleh komunitas.
 * Detail laporan per entri bisa kosong dulu (diisi kurator).
 */
const SCAM_LIST = [
  {
    id: "digicodestore",
    name: "DigiCode Store",
    url: "https://digicodestore.my.id",
    type: "Account Store",
    reportedVia: "Laporan komunitas Hermes",
    reason: "",   // detail kenapa scam — kosong untuk sementara, menunggu laporan
    reportedAt: "",
  },
];

// Ekspor untuk Node (dipakai scripts/check-status.js di GitHub Actions); di browser baris ini tidak berpengaruh.
if (typeof module !== "undefined" && module.exports) module.exports = PROVIDERS;
